version: "3.3"  # optional since v1.27.0
services:
  # This will connect to realsense devices and publish. Configured with config/l515/rspub_default.toml
  rs-pub:
    container_name: rs-pub
    env_file:
      - .env
    image: "jeremybyu/landing:${TAG}"
    privileged: true
    network_mode: "host"
    ipc: "host"
    user: "1000:1000"
    volumes:
      - $PWD:/opt/workspace
    entrypoint: [./scripts/launch/launch_rspub.sh]
    # command: ./bin/${ARCH}/rs-pub --log_dir=./logs --v=2 --config=config/l515/rspub_default.toml
  # This is an RPC Server that is also subscribing to any RGBD Images that are published. Configured with config/l515/rsintegrate_default.toml
  rs-integrate:
    container_name: rs-integrate
    env_file:
      - .env
    image: "jeremybyu/landing:${TAG}"
    privileged: true
    network_mode: "host"
    ipc: "host"
    user: "1000:1000"
    volumes:
      - $PWD:/opt/workspace
    depends_on:
        - rs-pub
    entrypoint: [./scripts/launch/launch_integrate.sh]
