name = "Default Settings for D435 and T265."
show_images = true
show_polygon = true
depth_auto_exposure = 0.0
depth_exposure = 8000.0

[[manual_streams]]
device_name = "Intel RealSense T265"
stream_name = "Pose"
width = 0
height = 0
framerate = 200
format = "6DOF"
active = true

[[pipeline_streams]]
device_name = "Intel RealSense D435i"
stream_name = "Depth"
width = 424
height = 240
framerate = 30
format = "Z16"
active = true

[[pipeline_streams]]
device_name = "Intel RealSense D435i"
stream_name = "Color"
width = 424
height = 240
framerate = 30
format = "BGR8"
active = false

[filters]

  [filters.decimation]
  active = false
  magnitude = 2.0

  [filters.disparity]
  active = true

  [filters.temporal]
  active = true
  smooth_alpha = 0.6
  smooth_delta = 60.0
  persistence_control = 2.0

  [filters.spatial]
  active = true
  smooth_alpha = 0.5
  smooth_delta = 20.0
  magnitude = 2.0
  hole_fill = 1.0

  [filters.align]
  active=true

[publish]

  [publish.depth]
  active = true
  rate = 1

  [publish.color]
  active = false
  rate = 1

  [publish.rgbd]
  active = false
  rate = 1

  [publish.pose]
  active = true
  rate = 1

  [publish.pointcloud]
  active = false
  color = true
  stride = 2
  rate = 1
