name = "Save Settings"
base_path = "data/realsense"
min_translate_change = 0.10 # meters
min_rotation_change= 10.0 # degrees

# WIP
[subscribe]

  [subscribe.depth]
  active = false

  [subscribe.color]
  active = false


  [subscribe.rgbd]
  active = true


  [subscribe.pose]
  active = true


  [subscribe.pointcloud]
  active = true

