name = "Save Settings"
base_path = "data/realsense" # Base path to save data, will create subfolders

# Only save data if sensor translation and rotation changed this much
min_translate_change = 0.10 # meters
min_rotation_change= 10.0 # degrees

# Will save data to all these subscribed topics
[subscribe]

  [subscribe.depth]
  active = true

  [subscribe.color]
  active = true

  [subscribe.rgbd]
  active = true

  [subscribe.pose]
  active = true

  [subscribe.pointcloud]
  active = true

