---
    name: Default settings for visualization of point cloud
    
    n_points: 1
    voxel_size: 0.02
    # Point Cloud Settings
    pointcloud: 
      color: "height" # colorize point cloud by: intensity, height, distance
      color_map: 'plasma'
    
    # 2D/3D View Settings
    view_image: # Settings for 2D image viewer
      active: true
      show_polygons: true
    view_3D: # Settings for 3D point cloud viewer
      active: true
      show_polygons: true
      line_radius: 0.10
    
    # Polygon Extraction Settings
    polygon: # Settings for polygons extraction
      polylidar: # Parameters we send to polylidar. Determine plane and polygon extracton from point clouds.
        lmax: 1.25 # maximum distance (m) between points in plane for spatial connection
        zThresh: 0.04 # triangles with z-height (m) less than this have normal filtering skipped. For sensor noise.
        normThresh: 0.985 # triangles whose normal is greater than X degrees are filtered acos(tri_norm * [0,0,1])
        normThreshMin: 0.90 # mininum level of planarity needed
        minTriangles : 3500 # mininum number of triangles in a plane
        minHoleVertices : 6 # mininum number of vertices in a hole to return
        alpha: 0.0 # must be set to 0.0 if using lmax
      postprocess: # post processing of polygons returned from polylidar for ground/obstacle identification
        filter: # Fitler polygons
          hole_area: # obstacle (holes in polygons) must have these characteristics
            min: 0.5   # m^2
            max: 40 # m^2
          hole_vertices: # obstacles (holes in polygons) must have these characteristics
            min: 3 # A linear ring has a mininum of 3 vertices
          plane_area: # planes must have these area
          min: 30 # m^2
          num_planes_allowed: 1 # TODO Only allow this many largest planes through
        # These parameters correspond to Shapely polygon geometry operations
        positive_buffer: 0.02 # m, Positvely expand polygon.  Fills in small holes
        buffer: 0.3 # m, Negative buffer to polygon. Expands holes and constricuts outer hull of polygon
        simplify: 0.2  # m, simplify edges of polygon
    
    # Recording Settings
    record:
      active: false # do we want to actively record a video
      directory: "data" # what directory to save the mp4
      stacked: true # whether to stack 2D Viewer and 3D Viewer images
    
    # Record Execution Timings to csv file
    timings:
      active: false
      directory: "data"
    