# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImageMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ImageMessage.proto',
  package='rspub_pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12ImageMessage.proto\x12\x08rspub_pb\x1a\x0c\x43ommon.proto\"\x80\x02\n\x0cImageMessage\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x13\n\x0bhardware_ts\x18\x04 \x01(\x01\x12\x0b\n\x03\x62pp\x18\x05 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x06 \x01(\x05\x12#\n\x0btranslation\x18\x07 \x01(\x0b\x32\x0e.rspub_pb.Vec3\x12 \n\x08rotation\x18\x08 \x01(\x0b\x32\x0e.rspub_pb.Vec4\x12\x19\n\x11image_data_second\x18\t \x01(\x0c\x12\x12\n\nbpp_second\x18\n \x01(\x05\x12\x15\n\rformat_second\x18\x0b \x01(\x05\x62\x06proto3')
  ,
  dependencies=[Common__pb2.DESCRIPTOR,])




_IMAGEMESSAGE = _descriptor.Descriptor(
  name='ImageMessage',
  full_name='rspub_pb.ImageMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_data', full_name='rspub_pb.ImageMessage.image_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='rspub_pb.ImageMessage.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='rspub_pb.ImageMessage.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hardware_ts', full_name='rspub_pb.ImageMessage.hardware_ts', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bpp', full_name='rspub_pb.ImageMessage.bpp', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='rspub_pb.ImageMessage.format', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translation', full_name='rspub_pb.ImageMessage.translation', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='rspub_pb.ImageMessage.rotation', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_data_second', full_name='rspub_pb.ImageMessage.image_data_second', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bpp_second', full_name='rspub_pb.ImageMessage.bpp_second', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format_second', full_name='rspub_pb.ImageMessage.format_second', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=303,
)

_IMAGEMESSAGE.fields_by_name['translation'].message_type = Common__pb2._VEC3
_IMAGEMESSAGE.fields_by_name['rotation'].message_type = Common__pb2._VEC4
DESCRIPTOR.message_types_by_name['ImageMessage'] = _IMAGEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageMessage = _reflection.GeneratedProtocolMessageType('ImageMessage', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEMESSAGE,
  '__module__' : 'ImageMessage_pb2'
  # @@protoc_insertion_point(class_scope:rspub_pb.ImageMessage)
  })
_sym_db.RegisterMessage(ImageMessage)


# @@protoc_insertion_point(module_scope)
