# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMUMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='IMUMessage.proto',
  package='rspub_pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10IMUMessage.proto\x12\x08rspub_pb\x1a\x0c\x43ommon.proto\"^\n\nIMUMessage\x12\x1c\n\x04gyro\x18\x01 \x01(\x0b\x32\x0e.rspub_pb.Vec3\x12\x1d\n\x05\x61\x63\x63\x65l\x18\x02 \x01(\x0b\x32\x0e.rspub_pb.Vec3\x12\x13\n\x0bhardware_ts\x18\x03 \x01(\x01\x62\x06proto3')
  ,
  dependencies=[Common__pb2.DESCRIPTOR,])




_IMUMESSAGE = _descriptor.Descriptor(
  name='IMUMessage',
  full_name='rspub_pb.IMUMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gyro', full_name='rspub_pb.IMUMessage.gyro', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accel', full_name='rspub_pb.IMUMessage.accel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hardware_ts', full_name='rspub_pb.IMUMessage.hardware_ts', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=138,
)

_IMUMESSAGE.fields_by_name['gyro'].message_type = Common__pb2._VEC3
_IMUMESSAGE.fields_by_name['accel'].message_type = Common__pb2._VEC3
DESCRIPTOR.message_types_by_name['IMUMessage'] = _IMUMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IMUMessage = _reflection.GeneratedProtocolMessageType('IMUMessage', (_message.Message,), {
  'DESCRIPTOR' : _IMUMESSAGE,
  '__module__' : 'IMUMessage_pb2'
  # @@protoc_insertion_point(class_scope:rspub_pb.IMUMessage)
  })
_sym_db.RegisterMessage(IMUMessage)


# @@protoc_insertion_point(module_scope)
