# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Integrate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Integrate.proto',
  package='rspub_pb',
  syntax='proto3',
  serialized_options=_b('\200\001\001'),
  serialized_pb=_b('\n\x0fIntegrate.proto\x12\x08rspub_pb\"K\n\x10IntegrateRequest\x12\r\n\x05scene\x18\x01 \x01(\t\x12(\n\x04type\x18\x02 \x01(\x0e\x32\x1a.rspub_pb.SceneRequestType\"H\n\x0e\x45xtractRequest\x12\r\n\x05scene\x18\x01 \x01(\t\x12\'\n\x04type\x18\x02 \x01(\x0e\x32\x19.rspub_pb.DataRequestType\"#\n\x11IntegrateResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t*<\n\x10SceneRequestType\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\n\n\x06REMOVE\x10\x01\x12\t\n\x05START\x10\x02\x12\x08\n\x04STOP\x10\x03*9\n\x0f\x44\x61taRequestType\x12\x08\n\x04MESH\x10\x00\x12\x0e\n\nPOINTCLOUD\x10\x01\x12\x0c\n\x08POLYGONS\x10\x02\x32\xa6\x01\n\x10IntegrateService\x12I\n\x0eIntegrateScene\x12\x1a.rspub_pb.IntegrateRequest\x1a\x1b.rspub_pb.IntegrateResponse\x12G\n\x0c\x45xtractScene\x12\x1a.rspub_pb.IntegrateRequest\x1a\x1b.rspub_pb.IntegrateResponseB\x03\x80\x01\x01\x62\x06proto3')
)

_SCENEREQUESTTYPE = _descriptor.EnumDescriptor(
  name='SceneRequestType',
  full_name='rspub_pb.SceneRequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=217,
  serialized_end=277,
)
_sym_db.RegisterEnumDescriptor(_SCENEREQUESTTYPE)

SceneRequestType = enum_type_wrapper.EnumTypeWrapper(_SCENEREQUESTTYPE)
_DATAREQUESTTYPE = _descriptor.EnumDescriptor(
  name='DataRequestType',
  full_name='rspub_pb.DataRequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MESH', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POINTCLOUD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POLYGONS', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=279,
  serialized_end=336,
)
_sym_db.RegisterEnumDescriptor(_DATAREQUESTTYPE)

DataRequestType = enum_type_wrapper.EnumTypeWrapper(_DATAREQUESTTYPE)
ADD = 0
REMOVE = 1
START = 2
STOP = 3
MESH = 0
POINTCLOUD = 1
POLYGONS = 2



_INTEGRATEREQUEST = _descriptor.Descriptor(
  name='IntegrateRequest',
  full_name='rspub_pb.IntegrateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scene', full_name='rspub_pb.IntegrateRequest.scene', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='rspub_pb.IntegrateRequest.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=104,
)


_EXTRACTREQUEST = _descriptor.Descriptor(
  name='ExtractRequest',
  full_name='rspub_pb.ExtractRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scene', full_name='rspub_pb.ExtractRequest.scene', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='rspub_pb.ExtractRequest.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=178,
)


_INTEGRATERESPONSE = _descriptor.Descriptor(
  name='IntegrateResponse',
  full_name='rspub_pb.IntegrateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='rspub_pb.IntegrateResponse.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=215,
)

_INTEGRATEREQUEST.fields_by_name['type'].enum_type = _SCENEREQUESTTYPE
_EXTRACTREQUEST.fields_by_name['type'].enum_type = _DATAREQUESTTYPE
DESCRIPTOR.message_types_by_name['IntegrateRequest'] = _INTEGRATEREQUEST
DESCRIPTOR.message_types_by_name['ExtractRequest'] = _EXTRACTREQUEST
DESCRIPTOR.message_types_by_name['IntegrateResponse'] = _INTEGRATERESPONSE
DESCRIPTOR.enum_types_by_name['SceneRequestType'] = _SCENEREQUESTTYPE
DESCRIPTOR.enum_types_by_name['DataRequestType'] = _DATAREQUESTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntegrateRequest = _reflection.GeneratedProtocolMessageType('IntegrateRequest', (_message.Message,), {
  'DESCRIPTOR' : _INTEGRATEREQUEST,
  '__module__' : 'Integrate_pb2'
  # @@protoc_insertion_point(class_scope:rspub_pb.IntegrateRequest)
  })
_sym_db.RegisterMessage(IntegrateRequest)

ExtractRequest = _reflection.GeneratedProtocolMessageType('ExtractRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTREQUEST,
  '__module__' : 'Integrate_pb2'
  # @@protoc_insertion_point(class_scope:rspub_pb.ExtractRequest)
  })
_sym_db.RegisterMessage(ExtractRequest)

IntegrateResponse = _reflection.GeneratedProtocolMessageType('IntegrateResponse', (_message.Message,), {
  'DESCRIPTOR' : _INTEGRATERESPONSE,
  '__module__' : 'Integrate_pb2'
  # @@protoc_insertion_point(class_scope:rspub_pb.IntegrateResponse)
  })
_sym_db.RegisterMessage(IntegrateResponse)


DESCRIPTOR._options = None

_INTEGRATESERVICE = _descriptor.ServiceDescriptor(
  name='IntegrateService',
  full_name='rspub_pb.IntegrateService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=339,
  serialized_end=505,
  methods=[
  _descriptor.MethodDescriptor(
    name='IntegrateScene',
    full_name='rspub_pb.IntegrateService.IntegrateScene',
    index=0,
    containing_service=None,
    input_type=_INTEGRATEREQUEST,
    output_type=_INTEGRATERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ExtractScene',
    full_name='rspub_pb.IntegrateService.ExtractScene',
    index=1,
    containing_service=None,
    input_type=_INTEGRATEREQUEST,
    output_type=_INTEGRATERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INTEGRATESERVICE)

DESCRIPTOR.services_by_name['IntegrateService'] = _INTEGRATESERVICE

# @@protoc_insertion_point(module_scope)
