# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Integrate_pb2 as Integrate__pb2


class IntegrateServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.IntegrateScene = channel.unary_unary(
        '/rspub_pb.IntegrateService/IntegrateScene',
        request_serializer=Integrate__pb2.IntegrateRequest.SerializeToString,
        response_deserializer=Integrate__pb2.IntegrateResponse.FromString,
        )
    self.ExtractScene = channel.unary_unary(
        '/rspub_pb.IntegrateService/ExtractScene',
        request_serializer=Integrate__pb2.IntegrateRequest.SerializeToString,
        response_deserializer=Integrate__pb2.IntegrateResponse.FromString,
        )


class IntegrateServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def IntegrateScene(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExtractScene(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IntegrateServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'IntegrateScene': grpc.unary_unary_rpc_method_handler(
          servicer.IntegrateScene,
          request_deserializer=Integrate__pb2.IntegrateRequest.FromString,
          response_serializer=Integrate__pb2.IntegrateResponse.SerializeToString,
      ),
      'ExtractScene': grpc.unary_unary_rpc_method_handler(
          servicer.ExtractScene,
          request_deserializer=Integrate__pb2.IntegrateRequest.FromString,
          response_serializer=Integrate__pb2.IntegrateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rspub_pb.IntegrateService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
