# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PoseMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PoseMessage.proto',
  package='rspub_pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11PoseMessage.proto\x12\x08rspub_pb\x1a\x0c\x43ommon.proto\"\xc0\x02\n\x0bPoseMessage\x12#\n\x0btranslation\x18\x01 \x01(\x0b\x32\x0e.rspub_pb.Vec3\x12 \n\x08velocity\x18\x02 \x01(\x0b\x32\x0e.rspub_pb.Vec3\x12$\n\x0c\x61\x63\x63\x65leration\x18\x03 \x01(\x0b\x32\x0e.rspub_pb.Vec3\x12 \n\x08rotation\x18\x04 \x01(\x0b\x32\x0e.rspub_pb.Vec4\x12(\n\x10\x61ngular_velocity\x18\x05 \x01(\x0b\x32\x0e.rspub_pb.Vec3\x12,\n\x14\x61ngular_acceleration\x18\x06 \x01(\x0b\x32\x0e.rspub_pb.Vec3\x12\x1a\n\x12tracker_confidence\x18\x07 \x01(\x05\x12\x19\n\x11mapper_confidence\x18\x08 \x01(\x05\x12\x13\n\x0bhardware_ts\x18\t \x01(\x01\"7\n\x0fPoseMessageList\x12$\n\x05poses\x18\x01 \x03(\x0b\x32\x15.rspub_pb.PoseMessageb\x06proto3')
  ,
  dependencies=[Common__pb2.DESCRIPTOR,])




_POSEMESSAGE = _descriptor.Descriptor(
  name='PoseMessage',
  full_name='rspub_pb.PoseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='translation', full_name='rspub_pb.PoseMessage.translation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='rspub_pb.PoseMessage.velocity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='rspub_pb.PoseMessage.acceleration', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='rspub_pb.PoseMessage.rotation', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='rspub_pb.PoseMessage.angular_velocity', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_acceleration', full_name='rspub_pb.PoseMessage.angular_acceleration', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracker_confidence', full_name='rspub_pb.PoseMessage.tracker_confidence', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mapper_confidence', full_name='rspub_pb.PoseMessage.mapper_confidence', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hardware_ts', full_name='rspub_pb.PoseMessage.hardware_ts', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=366,
)


_POSEMESSAGELIST = _descriptor.Descriptor(
  name='PoseMessageList',
  full_name='rspub_pb.PoseMessageList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='poses', full_name='rspub_pb.PoseMessageList.poses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=423,
)

_POSEMESSAGE.fields_by_name['translation'].message_type = Common__pb2._VEC3
_POSEMESSAGE.fields_by_name['velocity'].message_type = Common__pb2._VEC3
_POSEMESSAGE.fields_by_name['acceleration'].message_type = Common__pb2._VEC3
_POSEMESSAGE.fields_by_name['rotation'].message_type = Common__pb2._VEC4
_POSEMESSAGE.fields_by_name['angular_velocity'].message_type = Common__pb2._VEC3
_POSEMESSAGE.fields_by_name['angular_acceleration'].message_type = Common__pb2._VEC3
_POSEMESSAGELIST.fields_by_name['poses'].message_type = _POSEMESSAGE
DESCRIPTOR.message_types_by_name['PoseMessage'] = _POSEMESSAGE
DESCRIPTOR.message_types_by_name['PoseMessageList'] = _POSEMESSAGELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PoseMessage = _reflection.GeneratedProtocolMessageType('PoseMessage', (_message.Message,), {
  'DESCRIPTOR' : _POSEMESSAGE,
  '__module__' : 'PoseMessage_pb2'
  # @@protoc_insertion_point(class_scope:rspub_pb.PoseMessage)
  })
_sym_db.RegisterMessage(PoseMessage)

PoseMessageList = _reflection.GeneratedProtocolMessageType('PoseMessageList', (_message.Message,), {
  'DESCRIPTOR' : _POSEMESSAGELIST,
  '__module__' : 'PoseMessage_pb2'
  # @@protoc_insertion_point(class_scope:rspub_pb.PoseMessageList)
  })
_sym_db.RegisterMessage(PoseMessageList)


# @@protoc_insertion_point(module_scope)
